#!/bin/sh

NAME=assignment-7-mod
DIR=/home/root

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

do_start(){
    cd /etc/scull/scull_load
    /etc/scull/scull_load
    cd /etc/scull/module_load
    /etc/misc-modules/module_load hello
    /etc/misc-modules/module_load faulty
}

do_stop(){
    cd /etc/scull/scull_load
    /etc/scull/scull_unload
    cd /etc/scull/module_load
    /etc/misc-modules/module_unload hello
    /etc/misc-modules/module_unload faulty
}

do_status(){
    if lsmod | grep -q "^scull "; then
        echo "scull is loaded"
    else
        echo "scull is not loaded"
    fi

    if lsmod | grep -q "^hello "; then
        echo "hello is loaded"
    else
        echo "hello is not loaded"
    fi

    if lsmod | grep -q "^faulty "; then
        echo "faulty is loaded"
    else
        echo "faulty is not loaded"
    fi
}

case "$1" in
  status)
        do_status
        ;;
  start)
        echo -n "Loading assignment 7 modules: "$NAME
        do_start
        echo "."
        ;;
  stop)
        echo -n "Unloading assignment 7 modules: "$NAME
        do_stop
        echo "."
        ;;
  restart)
        echo -n "Reloading assignment 7 modules: "$NAME
        do_stop
        do_start
        echo "."
        ;;
  *)
        echo "Usage: "$1" {status|start|stop|restart}"
        exit 1
esac

exit 0